# Flutter 核心
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }
-keep class io.flutter.embedding.** { *; }

# Google Play Core（Flutter 按需加载组件，不使用但需要忽略缺失类）
-dontwarn com.google.android.play.core.**
-keep class com.google.android.play.core.** { *; }

# flutter_sound 原生层
-keep class com.dooboolab.** { *; }
-dontwarn com.dooboolab.**
-keep class xyz.canardoux.** { *; }
-dontwarn xyz.canardoux.**

# sqflite 数据库
-keep class com.tekartik.sqflite.** { *; }

# permission_handler
-keep class com.baseflow.permissionhandler.** { *; }

# shared_preferences
-keep class io.flutter.plugins.sharedpreferences.** { *; }

# path_provider
-keep class io.flutter.plugins.pathprovider.** { *; }

# JSON 序列化
-keepattributes *Annotation*
-keepclassmembers class * {
    @com.google.gson.annotations.SerializedName <fields>;
}

# 通用保护
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# 忽略所有缺失类警告（R8 missing_rules）
-ignorewarnings

# Auto-generated by R8 - missing Play Core classes
-dontwarn com.google.android.play.core.splitcompat.SplitCompatApplication
-dontwarn com.google.android.play.core.splitinstall.SplitInstallException
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManager
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManagerFactory
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest$Builder
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest
-dontwarn com.google.android.play.core.splitinstall.SplitInstallSessionState
-dontwarn com.google.android.play.core.splitinstall.SplitInstallStateUpdatedListener
-dontwarn com.google.android.play.core.tasks.OnFailureListener
-dontwarn com.google.android.play.core.tasks.OnSuccessListener
-dontwarn com.google.android.play.core.tasks.Task
